# Generated by Django 4.0.4 on 2022-06-06 10:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_shedule', models.CharField(max_length=255, verbose_name='График работы')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('altitude', models.CharField(max_length=255, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=255, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
