# Generated by Django 4.0.4 on 2022-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('on_carousel', models.BooleanField()),
                ('subtitle', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='index/%Y/%m/%d/')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
