# Generated by Django 4.0.4 on 2022-05-14 07:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexitem',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='index/%Y/%m/%d/'),
        ),
    ]
