# Generated by Django 4.0.4 on 2022-06-06 10:53

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='чпу')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название цвета')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступно')),
                ('is_novelty', models.BooleanField(default=False, verbose_name='Новинка')),
                ('sizes', multiselectfield.db.fields.MultiSelectField(choices=[('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58')], max_length=26, verbose_name='Размеры')),
                ('fabric_structure', models.CharField(max_length=200, verbose_name='Состав')),
                ('description', models.TextField(verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_preview', models.BooleanField(default=False, verbose_name='Показывать на превью')),
                ('vendor_code', models.CharField(max_length=200, verbose_name='артикул')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='чпу')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.color', verbose_name='цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'вариант продукта',
                'verbose_name_plural': 'варианты продукта',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('questioner', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('question_date', models.DateField(auto_now_add=True, verbose_name='дата вопроса')),
                ('answer', models.TextField(null=True, verbose_name='ответ')),
                ('answer_date', models.DateField(null=True, verbose_name='дата ответа')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.productvariant', verbose_name='вариант продукта')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-question_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'фотография варианта продукта',
                'verbose_name_plural': 'фотографии варианта продукта',
            },
        ),
    ]
