# Generated by Django 4.0.4 on 2022-05-21 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='product',
            new_name='product_variant',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='22golomonzin@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 5, 21, 12, 10, 49, 441637, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
