# Generated by Django 4.0.4 on 2022-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
