# Generated by Django 4.0.4 on 2022-05-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_product_question_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.productvariant'),
        ),
    ]
