# Generated by Django 4.0.4 on 2022-05-29 06:05

from django.db import migrations
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_profile.models.UserManager()),
            ],
        ),
    ]
