# Generated by Django 4.0.4 on 2022-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='someval', max_length=255, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_address',
            field=models.CharField(default='someval', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='locality',
            field=models.CharField(default='someval', max_length=255, verbose_name='Местоположение'),
            preserve_default=False,
        ),
    ]
